// composer-state.js — pure helpers shared across the composer.
//
// Holds no mutable state (that moved to composer-store.js in the Stage 3 Lit
// rewrite). What remains are the pure, framework-free functions the store and
// components lean on: the patient-URL builder, the app-root derivation, and the
// PID rules re-exported from the shared source of truth.
//
// PID validation lives in shared/pid.js — the single source shared with the
// patient app. Re-exported here so callers don't need to know which module owns
// the rules. Search matching lives in search.js; matchesQuery is re-exported
// for the same reason.

import { PID_PATTERN, pidWarning } from '../../shared/pid.js';
import { matchesQuery } from './search.js';

// Relative URL — resolves correctly at any base-path deployment.
// Generated by scripts/build-catalog.mjs from the config files.
export const CATALOG_URL = 'catalog.json';

export { PID_PATTERN, pidWarning, matchesQuery };

// ── URL generation ────────────────────────────────────────────────────────────

// buildUrl is pure: it derives a patient link from an explicit selection, never
// from module state. Returns null when nothing is selected.
//
// Item IDs are addresses: the patient app derives each item's config file from
// the token itself (configs/prod/<id>.json) and auto-fetches battery
// dependencies. The URL therefore carries no config list at all — only the
// ordered `items` and an optional `pid`.
//
// The pid is a patient identifier, so it rides in the URL *fragment* (`#pid=`)
// rather than the query string. Fragments are never sent in the HTTP request
// line, so the pid stays entirely client-side: out of Cloudflare/CDN access
// logs and out of the Referer header. Links generated the old way (`?pid=`)
// keep working — the patient app reads both forms (see src/app.js readPid()).
export function buildUrl({ selected = [], pid = '' } = {}, base = getAppRoot()) {
  if (selected.length === 0) return null;

  const url = `${base}?items=${selected.join(',')}`;
  if (pid.trim()) return `${url}#pid=${encodeURIComponent(pid.trim())}`;
  return url;
}

// Returns the app root URL (the page serving index.html), derived from the
// composer's own URL by stripping /composer/...
//   http://localhost:5173/composer/  → http://localhost:5173/
//   https://app.ezmadad.com/composer/ → https://app.ezmadad.com/
export function getAppRoot() {
  if (typeof window === 'undefined') return '/';
  return window.location.href.replace(/\/composer(\/.*)?$/, '/');
}
