// composer-state.js
// Shared mutable state, URL builder, and search matcher.
// All other composer modules import from here — nothing else holds state.
//
// PID validation is defined in shared/pid.js — single source of truth shared
// with the patient app. Re-exported here so existing callers don't need to
// know which module owns the rules.

import { PID_PATTERN, pidWarning } from '../../shared/pid.js';

// Relative URL — resolves correctly at any base path deployment.
// Generated by scripts/build-catalog.mjs from the config files.
export const CATALOG_URL = 'catalog.json';
export { PID_PATTERN, pidWarning };

export const state = {
  batteries:             [],       // [{ id, title, description, sourceUrl, ...catalog entry }]
  questionnaires:        [],       // [{ id, title, description, sourceUrl, ...catalog entry }]
  sourceByItem:          new Map(),// id → sourceUrl
  selected:              [],       // string[] in selection order
  pid:                   '',
  query:                 '',
  currentUrl:            null,     // kept in sync on every render/partial
  warnings:              [],       // string[] — load-time warnings only
  copied:                false,    // true for 2s after a successful clipboard write
};

// ── URL generation ────────────────────────────────────────────────────────────

export function buildUrl(base = getAppRoot()) {
  if (state.selected.length === 0) return null;

  // Only the selected items' sources go into the URL. Cross-config
  // dependencies declared by those configs are auto-fetched by the patient
  // app's loadConfig (BFS walk) — the composer doesn't duplicate that logic.
  const neededSources = new Set(
    state.selected.map(id => state.sourceByItem.get(id)).filter(Boolean)
  );

  const parts = [
    `configs=${[...neededSources].join(',')}`,
    `items=${state.selected.join(',')}`,
  ];
  if (state.pid.trim()) parts.push(`pid=${encodeURIComponent(state.pid.trim())}`);

  return `${base}?${parts.join('&')}`;
}

// Returns the app root URL (the page serving index.html).
// Derived from the composer's own URL by stripping /composer/...
// e.g. http://localhost:5173/composer/ → http://localhost:5173/
//      https://app.ezmadad.com/composer/ → https://app.ezmadad.com/
export function getAppRoot() {
  if (typeof window === 'undefined') return '/';
  return window.location.href.replace(/\/composer(\/.*)?$/, '/');
}

// ── PID validation ────────────────────────────────────────────────────────────
// Re-exported from shared/pid.js above. See that module for the rules.

// ── Search ────────────────────────────────────────────────────────────────────

export function matchesQuery(item, query) {
  if (!query) return true;
  const q = query.trim().toLowerCase();
  return (
    item.id.toLowerCase().includes(q) ||
    item.title.toLowerCase().includes(q) ||
    (item.description != null && item.description.toLowerCase().includes(q)) ||
    (item.keywords != null && item.keywords.some(k => k.toLowerCase().includes(q)))
  );
}
